---
http:
  - name: high-moctane/nextword-data
    description: Dataset for nextword.
    url: https://github.com/high-moctane/nextword-data/archive/refs/tags/large.tar.gz
    command:
      env:
        NEXTWORD_DATA_PATH: $XDG_CACHE_HOME/nextword/nextword-data-large
      link:
        - from: nextword-data-large
          to: $XDG_CACHE_HOME/nextword/nextword-data-large
github:
  - name: nurse/nkf
    description: Netword Kanji Filter
    owner: nurse
    repo: nkf
    command:
      build:
        steps:
          - make
          - make install prefix=~/.local
      link:
        - from: nkf
  - name: high-moctane/mocword-data
    description: Predict next words.
    owner: high-moctane
    repo: mocword-data
    release:
      name: mocword.sqlite.gz
      tag: eng20200217
    command:
      env:
        MOCWORD_DATA: $XDG_CACHE_HOME/mocword/mocword.sqlite
      link:
        - from: mocword.sqlite
          to: $XDG_CACHE_HOME/mocword/mocword.sqlite
  - name: koron/cmigemo
    description: C/Migemo
    owner: koron
    repo: cmigemo
    command:
      build:
        steps:
          - ./configure
          # NOTE: Require editing /etc/ld.so.conf.d/*.conf and execute `ldconfig`
          - make gcc-install prefix=~/.local FILTER_CP932='nkf -s' FILTER_EUCJP='nkf -e'
      link:
        - from: build/cmigemo
  - name: tats/w3m
    description: "Debian's w3m: WWW browsable pager"
    owner: tats
    repo: w3m
    command:
      build:
        steps:
          # NOTE: Require `apt install libgc-dev`
          - ./configure
          - make
          - make install prefix=~/.local
      link:
        - from: w3m
