#!/bin/sh

set -eu

stdin() {
  cmd="$1"
  shift
  while read -r stdin; do
    "$cmd" "$@" "$stdin"
  done
}

json="$(dirname "$0")/pipx.json"

if [ "$#" -ge 1 ]; then
  if [ "$1" = 'gen' ]; then
    pipx list --json \
      | gojq '.venvs | map_values(.metadata) | { inject: map_values(.injected_packages | keys | select(.[])), install: map(.main_package.package_or_url) }'
  else
    exit 1
  fi
else
  gojq -r '.install[]' < "$json" \
    | stdin printf 'pipx install %s\n' \
    | stdin eval
  gojq -r '.inject | to_entries | map([.key, .value] | flatten | join(" "))[]' < "$json" \
    | stdin printf 'pipx inject %s\n' \
    | stdin eval
fi
