
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [
  'iceberg.vim', 'lightline-gruvbox.vim', 'lightline-hybrid.vim',
  'tokyonight-vim', 'falcon', 'snow', 'elly.vim',
  'vim-vitamin-onec', 'rigel',
]
hook_add = '''
let g:lightline = {
      \ 'colorscheme': user#colorscheme#lightline(),
      \ 'active': {
      \   'right': [
      \     ['lineinfo'],
      \     ['percent'],
      \     ['colorscheme', 'fileformat', 'fileencoding', 'filetype'],
      \ ]},
      \ 'inactive': {
      \   'left': [
      \     ['filename', 'modified'],
      \ ]},
      \ 'component_function': {
      \   'colorscheme': 'user#lightline#colorscheme',
      \   'fileformat': 'user#lightline#file_format',
      \   'fileencoding': 'user#lightline#file_encoding',
      \ }}
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
call add(g:colorscheme_list, 'jellybeans')
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorscheme_list, 'iceberg')
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
call add(g:colorscheme_list, 'gruvbox')
'''

[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
call add(g:colorscheme_list, 'one')
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
call add(g:colorscheme_list, 'hybrid')
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
call add(g:colorscheme_list, 'onedark')
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
call add(g:colorscheme_list, 'nord')
'''

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
call add(g:colorscheme_list, 'tokyonight')
'''

[[plugins]]
repo = 'fenetikm/falcon'
hook_add = '''
call add(g:colorscheme_list, 'falcon')
'''

[[plugins]]
repo = 'haystackandroid/snow'
hook_add = '''
call add(g:colorscheme_list, 'snow')
'''

[[plugins]]
repo = 'yuttie/hydrangea-vim'
hook_add = '''
call add(g:colorscheme_list, 'hydrangea')
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
call add(g:colorscheme_list, 'elly')
'''

[[plugins]]
repo = 'gkapfham/vim-vitamin-onec'
hook_add = '''
call add(g:colorscheme_list, 'vitaminonec')
'''

[[plugins]]
repo = 'Rigellute/rigel'
hook_add = '''
call add(g:colorscheme_list, 'rigel')
'''
