
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [
  'lightline-lsp', 'vista.vim', 'iceberg.vim', 'lightline-gruvbox.vim',
  'lightline-hybrid.vim', 'tokyonight-vim', 'falcon', 'snow', 'elly.vim', 'rigel',
  'ayu-vim', 'vim-nightfly-guicolors', 'vim-snazzy', 'tender.vim',
]
hook_add = '''
" Runtime dein/settings/lightline.vim
SourceConf lightline.vim
'''

[[plugins]]
repo = 'halkn/lightline-lsp'
on_source = ['vim-lsp']

# TODO: it doesn't supprt terminal ansi colors
# https://github.com/nanotech/jellybeans.vim/blob/master/ansi-term-colors.txt
# https://github.com/akiyosi/jellybeans.vim/blob/master/colors/jellybeans.vim#L658
# https://github.com/akiyosi/jellybeans.vim
[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
call add(g:colorscheme_list, 'jellybeans')
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorscheme_list, 'iceberg')
let g:colorscheme_customize.iceberg = {
      \ 'highlight': {
      \   'String': #{ ctermfg: 144, guifg: '#a7b1a9', },
      \ }}
'''

# TODO: it doesn't supprt terminal ansi colors
# ttps://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L340
# ttps://github.com/gruvbox-community/gruvbox
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
call add(g:colorscheme_list, 'gruvbox')
let g:colorscheme_customize.gruvbox = {
      \ 'highlight': {
      \   'Visual': #{ ctermbg: 239, cterm: 'NONE',
      \                guibg: '#565656', gui: 'NONE', },
      \ }}
'''

[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
call add(g:colorscheme_list, 'one')
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
let g:hybrid_custom_term_colors = v:true
call add(g:colorscheme_list, 'hybrid')
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
call add(g:colorscheme_list, 'onedark')
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
call add(g:colorscheme_list, 'nord')
'''

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
call add(g:colorscheme_list, 'tokyonight')
'''

[[plugins]]
repo = 'fenetikm/falcon'
hook_add = '''
call add(g:colorscheme_list, 'falcon')
'''

[[plugins]]
repo = 'haystackandroid/snow'
hook_add = '''
call add(g:colorscheme_list, 'snow')
let g:colorscheme_customize.snow = {
      \ 'lightline': 'snow_dark',
      \ }
'''

[[plugins]]
repo = 'yuttie/hydrangea-vim'
hook_add = '''
call add(g:colorscheme_list, 'hydrangea')
let g:colorscheme_customize.hydrangea = {
      \ 'highlight': {
      \   'Constant': #{ ctermbg: 'NONE', guibg: 'NONE',  },
      \   'Number': #{ ctermbg: 'NONE', guibg: 'NONE',  },
      \   'SpecialKey': #{ ctermbg: 'NONE', guibg: 'NONE',  },
      \ }}
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
call add(g:colorscheme_list, 'elly')
'''

# [[plugins]]
# repo = 'gkapfham/vim-vitamin-onec'
# hook_add = '''
# call add(g:colorscheme_list, 'vitaminonec')
# '''

# TODO: it doesn't supprt terminal ansi colors
[[plugins]]
repo = 'Rigellute/rigel'
hook_add = '''
call add(g:colorscheme_list, 'rigel')
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
call add(g:colorscheme_list, 'ayu')
'''

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
call add(g:colorscheme_list, 'nightfly')
'''

[[plugins]]
repo = 'connorholyday/vim-snazzy'
hook_add = '''
call add(g:colorscheme_list, 'snazzy')
let g:colorscheme_customize.snazzy = {
      \ 'highlight': {
      \   'Visual': #{ ctermbg: 254, guibg: '#e4e4ee' },
      \ }}
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
call add(g:colorscheme_list, 'tender')
'''

[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
call add(g:colorscheme_list, 'dogrun')
'''

[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = '''
call add(g:colorscheme_list, 'gotham')
'''

