[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
set background=dark
autocmd user VimEnter * nested
      \ colorscheme iceberg
      \ | hi String ctermfg=144 guifg=#a7b1a9
'''
