
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = [
  'lightline-lsp', 'vista.vim', 'iceberg.vim', 'lightline-gruvbox.vim',
  'lightline-hybrid.vim', 'tokyonight-vim', 'falcon', 'snow', 'elly.vim', 'rigel',
  'ayu-vim', 'vim-nightfly-guicolors', 'vim-snazzy', 'tender.vim',
]
hook_add = '''
" Runtime dein/settings/lightline.vim
SourceConf lightline.vim
'''

[[plugins]]
repo = 'halkn/lightline-lsp'
on_source = ['vim-lsp']

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
call add(g:colorscheme_list, 'jellybeans')
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call add(g:colorscheme_list, 'iceberg')
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
call add(g:colorscheme_list, 'gruvbox')
'''

[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
call add(g:colorscheme_list, 'one')
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
call add(g:colorscheme_list, 'hybrid')
'''

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
call add(g:colorscheme_list, 'onedark')
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
call add(g:colorscheme_list, 'nord')
'''

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
call add(g:colorscheme_list, 'tokyonight')
'''

[[plugins]]
repo = 'fenetikm/falcon'
hook_add = '''
call add(g:colorscheme_list, 'falcon')
'''

[[plugins]]
repo = 'haystackandroid/snow'
hook_add = '''
call add(g:colorscheme_list, 'snow')
'''

[[plugins]]
repo = 'yuttie/hydrangea-vim'
hook_add = '''
call add(g:colorscheme_list, 'hydrangea')
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
call add(g:colorscheme_list, 'elly')
'''

# [[plugins]]
# repo = 'gkapfham/vim-vitamin-onec'
# hook_add = '''
# call add(g:colorscheme_list, 'vitaminonec')
# '''

[[plugins]]
repo = 'Rigellute/rigel'
hook_add = '''
call add(g:colorscheme_list, 'rigel')
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
call add(g:colorscheme_list, 'ayu')
'''

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
call add(g:colorscheme_list, 'nightfly')
'''

[[plugins]]
repo = 'connorholyday/vim-snazzy'
hook_add = '''
call add(g:colorscheme_list, 'snazzy')
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
call add(g:colorscheme_list, 'tender')
'''

[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
call add(g:colorscheme_list, 'dogrun')
'''

[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = '''
call add(g:colorscheme_list, 'gotham')
'''
