

repo = 'joshdick/onedark.vim'
on_if = 'g:current_colorscheme ==# "onedark"'
hook_add = '''
call add(g:colorscheme_list, 'onedark')
echo 'hoge'
let s:hoge = 'hoge'
function! s:hoge() abort
  execute 'echo' string(s:hoge)
endfunction
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
on_if = 'g:current_colorscheme ==# "nord"'
hook_add = '''
call add(g:colorscheme_list, 'nord')
'''

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
on_if = 'g:current_colorscheme ==# "tokyonight"'
hook_add = '''
call add(g:colorscheme_list, 'tokyonight')
'''

[[plugins]]
repo = 'fenetikm/falcon'
on_if = 'g:current_colorscheme ==# "falcon"'
hook_add = '''
call add(g:colorscheme_list, 'falcon')
'''

