[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim', 'pum.vim', 'lexima.vim']
on_event = ['InsertEnter']
hook_add = '''
" autocmd user CmdlineEnter : call user#ddc#cmdline_pre('<afile>')
" autocmd user CmdlineEnter / call user#ddc#cmdline_pre()
nnoremap : <Cmd>call timer_start(1, { -> user#ddc#cmdline_pre('') })<CR>:
'''
hook_source = '''
Runtime dein/settings/ddc.vim
'''

# sources

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = ['ddc.vim', 'vim-lsp']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'toml', 'help']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
on_source = 'ddc.vim'
hook_source = '''
" map! <C-u> <Plug>(skkeleton-toggle)
map! <C-j> <Plug>(skkeleton-toggle)
Runtime dein/settings/skkeleton.vim
'''

[[plugins]]
repo = 'gamoutatsumi/ddc-emoji'
on_ft = ['markdown', 'gitcommit']
on_source = 'ddc.vim'

[[plugins]]
repo = 'delphinus/ddc-tmux'
on_source = 'ddc.vim'

# filters

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

# popup windows

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
depends = ['denops.vim']
on_source = 'ddc.vim'
hook_source = '''
call signature_help#enable()
let g:lsp_signature_help_enabled = v:false
'''

