[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim', 'pum.vim', 'lexima.vim']
on_event = 'InsertEnter'
hook_source = '''
Runtime dein/settings/ddc.vim
'''
# sources

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'
depends = 'vim-lsp'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim', 'toml', 'help']
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
on_source = 'ddc.vim'

# filters

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-converter_truncate'
on_source = 'ddc.vim'



[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']
on_source = 'ddc.vim'
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_func = 'lsp#enable'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_source = '''
Runtime dein/settings/vim-lsp.vim
"call system(
"     \ g:lsp_settings_servers_dir . '/pyls-all/venv/bin/pip ' .
"     \ 'install pyls-mypy pyls-isort pyls-black'
"     \ )
'''
