[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
# on_source = ['denops.vim']
hook_source = '''
let s:patch_global = {}
let s:sourceOptions = {}
let s:sourceParams = {}
let s:kindOptions = {}

let s:patch_global.ui = 'std'
let s:sourceOptions._ = {
      \ 'ignoreCase': v:true,
      \ 'matchers': ['matcher_fzf'],
      \ }

let s:sourceParams.file_external = {
      \ 'cmd': ['git', 'ls-files', '-co', '--exclude-standard'],
      \ }

let s:kindOptions.file = {
      \ 'defaultAction': 'open',
      \ }
let s:kindOptions.readme_viewer = {
      \ 'defaultAction': 'open',
      \ }
let s:kindOptions.colorscheme = {
      \ 'defaultAction': 'set',
      \ }
let s:kindOptions.help = {
      \ 'defaultAction': 'open',
      \ }

let s:patch_global.sourceOptions = s:sourceOptions
let s:sourceOptions.sourceParams = s:sourceParams
let s:patch_global.kindOptions = s:kindOptions
call ddu#custom#patch_global(s:patch_global)
'''

[plugins.ftplugin]
ddu-std = '''
nnoremap <silent><buffer> <CR>
      \ <Cmd>call ddu#ui#std#do_action('itemAction')<CR>
nnoremap <silent><buffer> <Space>
      \ <Cmd>call ddu#ui#std#do_action('toggleSelectItem')<CR>
nnoremap <silent><buffer> i
      \ <Cmd>call ddu#ui#std#do_action('openFilterWindow')<CR>
nnoremap <silent><buffer> <C-l>
      \ <Cmd>call ddu#ui#std#do_action('refreshItems')<CR>
nnoremap <silent><buffer> q
      \ <Cmd>call ddu#ui#std#do_action('quit')<CR>
'''

ddu-std-filter = '''
inoremap <silent><buffer> <CR>
      \ <Esc><Cmd>close<CR>
nnoremap <silent><buffer> <CR>
      \ <Cmd>close<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['ddu.vim']
on_cmd = ['Ddu']

# UI

[[plugins]]
repo = 'Shougo/ddu-ui-std'
on_source = 'ddu.vim'

# filters

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
on_source = 'ddu.vim'

# kinds

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

# sources

[[plugins]]
repo = '4513echo/ddu-source-colorscheme'
on_source = 'ddu.vim'

[[plugins]]
repo = '4513echo/ddu-source-ghq'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_old'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-line'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

