[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
hook_source = '''
let s:patch_global = {}
let s:patch_global.ui = 'std'
call ddu#custom#patch_global(s:patch_global)
'''

[plugins.ftplugin]
ddu-std = '''
nnoremap <silent><buffer> <CR> <Cmd>call ddu#ui#std#do_map('doAction')<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
depends = ['ddu.vim']
on_cmd = ['Ddu']

