hook_add = '''
let g:python_highlight_all = v:true
let g:awk_is_gawk = v:true
let g:is_bash = v:true
let g:rust_bang_comment_leader = v:true
'''

[ftplugin]
_ = '''
setlocal formatoptions-=ro
setl formatoptions+=mMBl
'''
typescript = '''
nnoremap <buffer> <Leader><C-r> <Cmd>call denops#server#restart()<CR>
'''
python = '''
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal smarttab
setlocal expandtab
setlocal nosmartindent
'''
help = '''
setlocal iskeyword+=:#-
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_if = '!has("patch-8.2.3520")'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['vim', 'css', 'scss', 'sass']

[[plugins]]
repo = 'lark-parser/vim-lark-syntax'
on_ft = ['lark']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'typescript', 'rust']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_add = '''
Runtime dein/settings/vim-lsp.vim
'''
