
# for testing vim-readme-viewer

[[plugins]]
repo = 'k-takata/minpac'

[[plugins]]
repo = 'junegunn/vim-plug'

[[plugins]]
repo = 'wbthomason/packer.nvim'

##############################

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'thinca/vim-localrc'
hook_add = '''
let g:localrc_filename = '.vimrc.local'
'''

[[plugins]]
repo = 'obcat/vim-sclow'
if = '!has("nvim")'
hook_add = '''
let g:sclow_hide_full_length = v:true
'''

[[plugins]]
repo = 'obcat/vim-hitspop'
if = '!has("nvim")'
hook_add = '''
let g:hitspop_line = 'winbot'
autocmd user ColorScheme *
      \ hi link hitspopErrormsg ErrorMsg
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let s:context_filetypes = context_filetype#default_filetypes()
call remove(s:context_filetypes, 'markdown')
call extend(s:context_filetypes, {'markdown': values(map(
      \ {'\(\h\w*\)': '\1', 'viml': 'vim'},
      \ { key, val -> {
      \   'start': '^\s*```\s*' .. key,
      \   'end': '^\s*```$',
      \   'filetype': val,
      \ } }))})
let g:context_filetype#filetypes = s:context_filetypes
let g:context_filetype#ignore_patterns = {
      \ 'toml': ['^\s*#\s*'],
      \ }
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
let g:clever_f_ignore_case = v:true
let g:clever_f_smart_case = v:true
let g:clever_f_use_migemo = v:true
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'mattn/vim-molder'
[plugins.ftplugin]
molder = '''
nmap <buffer> <C-r> <Plug>(molder-reload)
'''

[[plugins]]
repo = 'mattn/vim-molder-operations'
depends = ['vim-molder']

[[plugins]]
repo = 'osyo-manga/vim-jplus'
on_map = { nx = '<Plug>(jplus' }
hook_add = '''
nmap J <Plug>(jplus)
xmap J <Plug>(jplus)
'''

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
SourceConf submode.vim
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_source = ['vim-lsp-settings']
on_ft = [
  'python', 'typescript', 'typescriptreact',
  'rust', 'markdown', 'yaml', 'json',
]
hook_add = '''
autocmd user BufNewFile,BufRead
      \ *.py,*.ts,*.tsx,*.rs,*.md
      \ call lsp#enable()
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-lsp']
hook_add = '''
" Runtime dein/settings/vim-lsp.vim
SourceConf vim-lsp.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" Runtime dein/settings/lightline.vim
SourceConf lightline.vim
'''

[[plugins]]
repo = 'halkn/lightline-lsp'
on_source = ['lightline.vim', 'vim-lsp']

[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'itchyny/vim-highlighturl'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
let g:tmux_navigator_no_mappings = v:true

nnoremap <C-w>h <Cmd>TmuxNavigateLeft<CR>
nnoremap <C-w>j <Cmd>TmuxNavigateDown<CR>
nnoremap <C-w>k <Cmd>TmuxNavigateUp<CR>
nnoremap <C-w>l <Cmd>TmuxNavigateRight<CR>
'''

[[plugins]]
repo = 'markonm/traces.vim'

# TODO: send PR to use `hi def` instead of `hlexists()`
[[plugins]]
repo = 'hrsh7th/vim-seak'
hook_add = '''
let g:seak_enabled = v:true
let g:seak_marks = split('ASDFHJKL', '.\zs')
let g:seak_auto_accept = v:true
autocmd user ColorScheme *
      \ hi def SeakChar gui=bold,underline guifg=Red guibg=NONE
'''

