[[plugins]]
repo = 'cohama/lexima.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
rev = 'dev'
hook_source = '''
let g:lexima_no_default_rules = v:true
" Runtime dein/settings/lexima.vim
" autocmd user FileType * SourceConf lexima.vim
SourceConf lexima.vim
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
type__depth = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_add = '''
let g:quickrun_config = {
      \ '_': {
      \   'runner': 'job',
      \   'outputter/buffer/opener': 'botright 10split',
      \   'outputter/buffer/close_on_empty': v:true,
      \   'hook/time/enable': v:true,
      \ },
      \ 'typescript': {
      \   'type': 'typescript/deno',
      \ },
      \ }
'''
[plugins.ftplugin]
quickrun = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = ['Capture', 'CaptureJson']
hook_add = '''
command! -bang -bar -nargs=1 -complete=var CaptureJson
      \ : execute 'Capture<bang> echo json_encode(<args>)'
      \ | if &filetype ==# 'capture'
      \ |   execute '%!jq'
      \ | endif
'''
[plugins.ftplugin]
capture = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = { nx = '<Plug>(caw' }
hook_add = '''
nmap <silent> <Leader>c <Plug>(caw:hatpos:toggle)
xmap <silent> <Leader>c <Plug>(caw:hatpos:toggle)
'''


[[plugins]]
repo = 'thinca/vim-scall'
on_func = ['S']
hook_add = '''
let g:scall_function_name = 'S'
'''

[[plugins]]
repo = 'cocopon/colorswatch.vim'
on_cmd = ['ColorSwatchGenerate']

[[plugins]]
repo = 'cocopon/inspecthi.vim'
depends = ['colorswatch.vim']
on_cmd = ['Inspecthi']

[[plugins]]
repo = 'powerman/vim-plugin-AnsiEsc'
on_cmd = ['AnsiEsc']

[[plugins]]
repo = 'haya14busa/vim-edgemotion'
on_map = { nx = '<Plug>(edgemotion' }
hook_add = '''
nmap <C-j> <Plug>(edgemotion-j)
nmap <C-k> <Plug>(edgemotion-k)
xmap <C-j> <Plug>(edgemotion-j)
xmap <C-k> <Plug>(edgemotion-k)
'''

# [[plugins]]
# repo = 'junegunn/fzf'
# if = 'executable("fzf")'

# [[plugins]]
# repo = 'junegunn/fzf.vim'
# depends = ['fzf']
# if = 'executable("fzf")'

# [[plugins]]
# repo = 'guns/xterm-color-table.vim'
# on_cmd = ['XtermColorTable']

# [[plugins]]
# repo = 'pocke/keycast.vim'
# if = '!has("nvim")'
# on_cmd = ['KeycastStart', 'KeycastStop']
# depends = ['vanner']

# [[plugins]]
# repo = 'pocke/vanner'

# [[plugins]]
# repo = 'thinca/vim-scouter'
# on_cmd = ['Scouter']
# on_func = ['Scouter']
# hook_add = '''
# command! Scouter echo Scouter(g:config_home)
# '''

# [[plugins]]
# repo = 'rbtnn/vim-coloredit'
# if = '!has("nvim")'
# on_cmd = ['ColorEdit']

# [[plugins]]
# repo = 'reireias/vim-cheatsheet'
# on_cmd = ['Cheat']
# hook_add = '''
# let g:cheatsheet#cheat_file = g:config_home .. '/doc/cheatsheet.md'
# '''

# [[plugins]]
# repo = 'kat0h/bufpreview.vim'
# depends = ['denops.vim']
# hook_add = '''
# let g:bufpreview_server_host = '0.0.0.0'
# let g:bufpreview_server_port = 8888
# '''

# [[plugins]]
# repo = 'skanehira/badapple.vim'
# if = '!has("nvim")'
# on_cmd = ['BadApple']

# [[plugins]]
# repo = 'mattn/benchvimrc-vim'
# on_cmd = ['BenchVimrc']
