[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_add = '''
let g:lexima_accept_pum_with_enter = 1
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['help']
hook_add = '''
set helplang=ja,en
set keywordprg=:help
'''
type__depth = 1

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
let g:context_filetype#ignore_patterns = {
  \ 'toml': ['^\s*#\s*'],
  \ }
'''

[[plugins]]
repo = 'guns/xterm-color-table.vim'
on_cmd = ['XtermColorTable']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
hook_add = '''
let g:quickrun_config = {
  \"_" : {
  \ "runner" : "vimproc",
  \ "runner/vimproc/updatetime" : 60,
  \ "outputter/buffer/split" : "botright 8sp",
  \ "outputter/buffer/close_on_empty" : 1
  \ },
  \ }
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['jellybeans.vim', 'iceberg.vim']
hook_add = '''
let g:lightline = {
  \ 'colorscheme' : 'iceberg'
  \ }
'''

[[plugins]]
repo = 'thinca/vim-scouter'
on_cmd = ['Scouter']

