---
packages:
  # init: a

  # init: b

  # init: c

  # init: d

  # init: e

  # init: f

  # init: g

  # init: h
  - type: github_content
    repo_owner: holman
    repo_name: spark
    path: spark
    description: ▁▂▃▅▂▇ in your shell

  # init: i

  # init: j
  - type: github_content
    repo_owner: JosefZIla
    repo_name: bash2048
    path: bash2048.sh
    description: Bash implementation of 2048 game
    format: raw
    files:
      - name: bash2048.sh
    supported_envs:
      - darwin
      - linux

  # init: k

  # init: l

  # init: m
  - type: github_release
    repo_owner: machikado-network
    repo_name: sakura
    asset: "{{.Version}}-{{.Arch}}-{{.OS}}"
    format: raw
    replacements:
      amd64: x86_64
      arm64: aarch64
      linux: unknown-linux-gnu
    supported_envs:
      - linux

  # init: n

  # init: o

  # init: p
  - type: github_content
    repo_owner: pipeseroni
    repo_name: pipes.sh
    path: pipes.sh
    description: Animated pipes terminal screensaver
    format: raw
    supported_envs:
      - darwin
      - linux

  # init: q

  # init: r
  - type: go_install
    repo_owner: rrethy
    repo_name: hexokinase
    description: Fast text scraper to find and convert colours (hex, rgb, rgb, hsl, web colours, custom patterns, etc.) into hex values

  # init: s
  - type: github_content
    repo_owner: sheepla
    repo_name: fzpac
    path: fzpac
    description: Arch Linux package finder with fzf

  # init: t
  - type: github_content
    repo_owner: thinca
    repo_name: ciw
    path: bin/ciw
    description: A wrapper to install cli binary from language associated package manager

  # init: u

  # init: v

  # init: w

  # init: x

  # init: y

  # init: z
