---
packages:
  # init: a

  # init: b

  # init: c

  # init: d

  # init: e
  - type: github_release
    repo_owner: elixir-lang
    repo_name: elixir
    description: Elixir is a dynamic, functional language designed for building scalable and maintainable applications

  # init: f

  # init: g
  - type: github_release
    repo_owner: guptarohit
    repo_name: asciigraph
    asset: 'asciigraph_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}'
    description: Go package to make lightweight ASCII line graph ╭┈╯ in command line apps with no other dependencies
    format: tar.gz
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
      arm: armv6
      386: i386

  # init: h
  - type: github_release
    repo_owner: high-moctane
    repo_name: mocword
    asset: 'mocword-{{.Arch}}-{{.OS}}'
    replacements:
      darwin: unknown-apple-darwin
      linux: unknown-linux-musl
      amd64: x86_64
      arm64: aarch64
    version_constraint: 'semver(">= 0.2.0")'
    version_overrides:
      - version_constraint: 'semver("< 0.2.0")'
        supported_if: not (GOOS == "linux" and GOARCH == "arm64")
  - type: github_content
    repo_owner: holman
    repo_name: spark
    path: spark
    description: ▁▂▃▅▂▇ in your shell

  # init: i

  # init: j
  - type: github_content
    repo_owner: JosefZIla
    repo_name: bash2048
    path: bash2048.sh
    description: Bash implementation of 2048 game
    format: raw
    files:
      - name: bash2048.sh
  - type: github_content
    repo_owner: junegunn
    repo_name: fzf
    name: junegunn/fzf/bin/fzf-tmux
    path: bin/fzf-tmux
    description: fzf-tmux is a bash script that opens fzf in a tmux pane
    files:
      - name: fzf-tmux

  # init: k
  - type: github_release
    repo_owner: ko1nksm
    repo_name: getoptions
    asset: getoptions
    description: An elegant option/argument parser for shell scripts (full support for bash and all POSIX shells)

  # init: l

  # init: m
  - type: github_release
    repo_owner: mgdm
    repo_name: htmlq
    asset: "htmlq-{{.Arch}}-{{.OS}}.{{.Format}}"
    supported_if: not (GOOS == "linux" and GOARCH == "arm64")
    description: Like jq, but for HTML
    replacements:
      amd64: x86_64
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
  - type: github_release
    repo_owner: microsoft
    repo_name: ripgrep-prebuilt
    asset: "ripgrep-{{.Version}}-{{.Arch}}-{{.OS}}.tar.gz"
    description: Builds ripgrep on Azure Pipelines for multiple platforms and makes the binaries available as Github releases
    replacements:
      darwin: apple-darwin
      windows: pc-windows-msvc
      linux: unknown-linux-musl
      arm64: aarch64
      amd64: x86_64
    files:
      - name: rg

  # init: n
  - name: nodejs/node
    type: http
    repo_owner: nodejs
    repo_name: node
    rosetta2: true
    url: "https://nodejs.org/dist/{{.Version}}/node-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz"
    link: https://nodejs.org/
    description: Node.js JavaScript runtime
    replacements:
      amd64: x64
    files:
      - name: corepack
        src: "node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/corepack"
      - name: node
        src: "node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/node"
      - name: npm
        src: "node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/npm"
      - name: npx
        src: "node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/npx"

  # init: o

  # init: p
  - type: github_release
    repo_owner: pen-lang
    repo_name: pen
    asset: "pen-{{trimV .Version}}-{{.Arch}}-{.OS}.tar.xz"
    rosetta2: true
    supported_if: not (GOOS == "linux" and GOARCH == "arm64")
    description: The programming language for scalable software development
    replacements:
      darwin: apple-darwin
      linux: unknown-linux-gnu
      amd64: x86_64
    files:
      - name: pen
        src: target/release/pen

  # init: q

  # init: r
  - type: github_release
    repo_owner: rhysd
    repo_name: vim-startuptime
    asset: "vim-startuptime_{{trimV .Version}}_{{.OS}}_{{.Arch}}.{{.Format}}"
    format: tar.gz
    overrides:
      - goos: windows
        format: zip
  - type: http
    repo_owner: rust-lang
    repo_name: rust
    url: "https://static.rust-lang.org/dist/rust-{{.Version}}-{{.Arch}}-{{.OS}}.tar.gz"
    description: Empowering everyone to build reliable and efficient software
    replacements:
      darwin: apple-darwin
      linux: unknown-linux-musl
      freebsd: unknown-freebsd
      netbsd: unknown-netbsd
      amd64: x86_64
      arm64: aarch64
      386: i686
    files:
      - name: cargo
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/cargo/bin/cargo"
      - name: clippy-driver
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/clippy-preview/bin/clippy-driver"
      - name: cargo-clippy
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/clippy-preview/bin/cargo-clippy"
      - name: rls
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rls-preview/bin/rls"
      - name: rust-demangler
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rust-demangler-preview/bin/rust-demangler"
      - name: rustdoc
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rustdoc"
      - name: rust-lldb
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-lldb"
      - name: rustc
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rustc"
      - name: rust-gdbgui
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-gdbgui"
      - name: rust-gdb
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-gdb"
      - name: rustfmt
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustfmt-preview/bin/rustfmt"
      - name: cargo-fmt
        src: "rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustfmt-preview/bin/cargo-fmt"

  # init: s
  - type: github_content
    repo_owner: sheepla
    repo_name: fzpac
    path: fzpac
    description: Arch Linux package finder with fzf

  # init: t
  - type: github_content
    repo_owner: thinca
    repo_name: ciw
    path: bin/ciw
    description: A wrapper to install cli binary from language associated package manager

  # init: u

  # init: v
  - type: github_release
    repo_owner: vishaltelangre
    repo_name: ff
    asset: 'find-files-{{.Version}}-{{.Arch}}-{{.OS}}.tar.gz'
    description: Find files (ff) by name, fast!
    rosetta2: true
    replacements:
      darwin: apple-darwin
      linux: unknown-linux-musl
      arm64: aarch64
      amd64: x86_64
    overrides:
      - goos: linux
        goarch: arm64
        replacements:
          linux: unknown-linux-gnu

  # init: w

  # init: x

  # init: y

  # init: z
