---
packages:
  # init: a

  # init: b

  # init: c

  # init: d

  # init: e

  # init: f

  # init: g
  - type: go_install
    repo_owner: greymd
    repo_name: ojichat
    description: おじさんがLINEやメールで送ってきそうな文を生成する

  # init: h
  - type: github_content
    repo_owner: holman
    repo_name: spark
    path: spark
    description: ▁▂▃▅▂▇ in your shell

  # init: i
  - type: github_release
    repo_owner: itchyny
    repo_name: maze
    asset: maze_{{.Version}}_{{.OS}}_{{.Arch}}.{{.Format}}
    format: zip
    description: A maze command written in Go
    overrides:
      - goos: linux
        format: tar.gz
    files:
      - name: maze
        src: maze_{{.Version}}_{{.OS}}_{{.Arch}}/maze

  # init: j
  - type: github_content
    repo_owner: JosefZIla
    repo_name: bash2048
    path: bash2048.sh
    description: Bash implementation of 2048 game
    format: raw
    files:
      - name: bash2048.sh

  # init: k

  # init: l

  # init: m
  - type: github_release
    repo_owner: machikado-network
    repo_name: sakura
    asset: "{{.Version}}-{{.Arch}}-{{.OS}}"
    format: raw
    replacements:
      amd64: x86_64
      arm64: aarch64
      linux: unknown-linux-gnu
    supported_envs:
      - linux

  # init: n
  - type: http
    repo_owner: nodejs
    repo_name: node
    rosetta2: true
    url: https://nodejs.org/dist/{{.Version}}/node-{{.Version}}-{{.OS}}-{{.Arch}}.tar.gz
    link: https://nodejs.org/
    description: Node.js JavaScript runtime
    replacements:
      amd64: x64
    files:
      - name: corepack
        src: node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/corepack
      - name: node
        src: node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/node
      - name: npm
        src: node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/npm
      - name: npx
        src: node-{{.Version}}-{{.OS}}-{{.Arch}}/bin/npx

  # init: o

  # init: p

  # init: q

  # init: r
  - type: go_install
    repo_owner: rrethy
    repo_name: hexokinase
    description: Fast text scraper to find and convert colours (hex, rgb, rgb, hsl, web colours, custom patterns, etc.) into hex values
  - type: http
    repo_owner: rust-lang
    repo_name: rust
    url: https://static.rust-lang.org/dist/rust-{{.Version}}-{{.Arch}}-{{.OS}}.tar.gz
    description: Empowering everyone to build reliable and efficient software
    replacements:
      darwin: apple-darwin
      linux: unknown-linux-musl
      freebsd: unknown-freebsd
      netbsd: unknown-netbsd
      amd64: x86_64
      arm64: aarch64
      386: i686
    files:
      - name: cargo
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/cargo/bin/cargo
      - name: clippy-driver
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/clippy-preview/bin/clippy-driver
      - name: cargo-clippy
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/clippy-preview/bin/cargo-clippy
      - name: rls
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rls-preview/bin/rls
      - name: rust-demangler
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rust-demangler-preview/bin/rust-demangler
      - name: rustdoc
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rustdoc
      - name: rust-lldb
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-lldb
      - name: rustc
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rustc
      - name: rust-gdbgui
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-gdbgui
      - name: rust-gdb
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustc/bin/rust-gdb
      - name: rustfmt
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustfmt-preview/bin/rustfmt
      - name: cargo-fmt
        src: rust-{{.Version}}-{{.Arch}}-{{.OS}}/rustfmt-preview/bin/cargo-fmt

  # init: s
  - type: github_content
    repo_owner: sheepla
    repo_name: fzpac
    path: fzpac
    description: Arch Linux package finder with fzf

  # init: t
  - type: github_content
    repo_owner: thinca
    repo_name: ciw
    path: bin/ciw
    description: A wrapper to install cli binary from language associated package manager

  # init: u

  # init: v

  # init: w

  # init: x

  # init: y

  # init: z
