#!/bin/sh

set -ue

case $1 in
  gen*)
    shift
    gojq -r --yaml-input 'include "4513echo/aqua"; generate' \
      < ./aqua.yaml \
      | while read -r package; do
        case $* in
          -e | --exec)
            sleep 0.5
            aqua generate "$package"
            ;;
          *)
            echo "$package"
            ;;
        esac
      done
    ;;
  desc*)
    gojq -r --yaml-input 'include "4513echo/aqua"; description' \
      < ./experimental.yaml
    ;;
esac
