#!/usr/bin/env bash

# based on https://qiita.com/ik-fib/items/55edad2e5f5f06b3ddd1
GIT_ROOT="$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)"
HOOK_NAME="$(basename "$0")"
LOCAL_HOOK="$GIT_ROOT/.git/hooks/$HOOK_NAME"

if [ -e "$LOCAL_HOOK" ]; then
  # shellcheck source=/dev/null
  source "$LOCAL_HOOK"
fi

LOGFILE="$(mktemp)"
# echo "$LOGFILE" 1>&2
exec 1> >(tee -a "$LOGFILE" >&2)
exec 2> >(tee -a "$LOGFILE" >&2)
trap 'rm -f $LOGFILE' EXIT

check() {
  printf '\e[1m●\e[m \e[1m%s\e[m\n' "$1"
  shift
  if eval "$*"; then
    :
  fi
  if [ -n "${GITHOOK_IGNORE:-}" ]; then
    :
  fi
}

error() {
  local len
  len="$(wc -l < "$LOGFILE")"
  printf '\e[%dF\e[1;31m✗\e[%dE\e[31m\e[1E' "$len" "$len"
  printf 'Error\e[m: %s\n' "$*"
  exit 1
}

check_end() {
  local len
  len="$(wc -l < "$LOGFILE")"
  printf '\e[%dF\e[1;32m✔︎\e[m\e[%dE' "$len" "$len"
  printf '' > "$LOGFILE"
}
