[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim']
on_event = 'InsertEnter'
hook_source = '''
runtime! dein/settings/ddc.vim
'''

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'
depends = 'vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_func = 'lsp#enable'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_add = '''
runtime! dein/settings/vim-lsp.vim
'''
hook_post_source = '''
call system(
      \ '${XDG_DATA_HOME:-$HOME/.local/share/}vim-lsp-settings/ ' .
      \ 'servers/pyls-all/venv/bin/pip ' .
      \ 'install pyls-mypy pyls-isort pyls-black'
      \ )
'''
