[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''
let g:lexima_enable_newline_rules=0
'''
on_i = 1

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
on_i = 1

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['help']
hook_add = '''
set helplang=ja,en
set keywordprg=:help
'''

[[plugins]]
repo = 'guns/xterm-color-table.vim'
on_cmd = ['XtermColorTable']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_source = ['vimproc.vim']
hook_add = '''
  let g:quickrun_config = {
    \"_" : {
    \ "runner" : "vimproc",
    \ "runner/vimproc/updatetime" : 60,
    \ "outputter/buffer/split" : "botright 8sp",
    \ "outputter/buffer/close_on_empty" : 1
    \ },
    \}
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
on_source = ['jellybeans.vim', 'iceberg.vim']
hook_source = '''
set laststatus=2
set noshowmode
set showcmd
set ruler
let g:lightline = {
  \ 'colorscheme': 'iceberg'
  \ }
'''

[[plugins]]
repo = 'thinca/vim-scouter'
