
[[plugins]]
repo = '4513echo/vim-colors-hatsunemiku'
[[plugins.colorschemes]]
name = 'hatsunemiku'
# [[plugins.colorschemes]]
# name = 'hatsunemiku_light'

[[plugins]]
repo = 'cormacrelf/vim-colors-github'
[[plugins.colorschemes]]
name = 'github'
[plugins.colorschemes.highlight]
EndOfBuffer = { ctermfg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'embark-theme/vim'
name = 'embark-theme'
[[plugins.colorschemes]]
name = 'embark'

[[plugins]]
repo = 'fcpg/vim-orbital'
[[plugins.colorschemes]]
name = 'orbital'
[plugins.colorschemes.highlight]
String = { ctermbg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'felipec/vim-felipec'
[[plugins.colorschemes]]
name = 'felipec'
[plugins.colorschemes.highlight]
NonText = { ctermbg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'KabbAmine/yowish.vim'
hook_add = '''
let g:yowish = {
      \ 'ctrlp': v:false,
      \ 'unite': v:false,
      \ 'nerdtree': v:false,
      \ 'agit': v:false,
      \ 'signjk': v:false,
      \ }
'''
[[plugins.colorschemes]]
name = 'yowish'

[[plugins]]
repo = 'Rigellute/rigel'
[[plugins.colorschemes]]
name = 'rigel'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
[[plugins.colorschemes]]
name = 'nord'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
[[plugins.colorschemes]]
name = 'ayu'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
[[plugins.colorschemes]]
name = 'nightfly'

[[plugins]]
repo = 'challenger-deep-theme/vim'
name = 'challenger-deep-theme'
[[plugins.colorschemes]]
name = 'challenger_deep'

[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins.colorschemes]]
name = 'iceberg'
[plugins.colorschemes.highlight]
String = { ctermfg = 144, guifg = '#a7b1a9' }

[[plugins]]
repo = 'connorholyday/vim-snazzy'
[[plugins.colorschemes]]
name = 'snazzy'
[plugins.colorschemes.highlight]
String = { ctermfg = 254, guifg = '#e4e4ee' }

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
[[plugins.colorschemes]]
name = 'dracula'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'
[[plugins.colorschemes]]
name = 'palenight'

[[plugins]]
repo = 'fenetikm/falcon'
[[plugins.colorschemes]]
name = 'falcon'

[[plugins]]
repo = 'franbach/miramare'
[[plugins.colorschemes]]
name = 'miramare'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
[[plugins.colorschemes]]
name = 'tokyonight'

[[plugins]]
repo = 'habamax/vim-gruvbit'
[[plugins.colorschemes]]
name = 'gruvbit'

[[plugins]]
repo = 'haishanh/night-owl.vim'
[[plugins.colorschemes]]
name = 'night-owl'
lightline = 'nightowl'

[[plugins]]
repo = 'haystackandroid/snow'
[[plugins.colorschemes]]
name = 'snow'
lightline = 'snow_dark'

[[plugins]]
repo = 'haystackandroid/stellarized'
[[plugins.colorschemes]]
name = 'stellarized'
lightline = 'stellarized_dark'

[[plugins]]
repo = 'jacoborus/tender.vim'
[[plugins.colorschemes]]
name = 'tender'

[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins.colorschemes]]
name = 'onedark'

[[plugins]]
repo = 'karoliskoncevicius/sacredforest-vim'
[[plugins.colorschemes]]
name = 'sacredforest'

[[plugins]]
repo = 'kyoh86/momiji'
[[plugins.colorschemes]]
name = 'momiji'

[[plugins]]
repo = 'lifepillar/vim-solarized8'
[[plugins.colorschemes]]
name = 'solarized8'
lightline = 'solarized'

[[plugins]]
repo = 'lighthaus-theme/vim-lighthaus'
[[plugins.colorschemes]]
name = 'lighthaus'

[[plugins]]
repo = 'mhartington/oceanic-next'
[[plugins.colorschemes]]
name =  'OceanicNext'
lightline = 'oceanicnext'

[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins.colorschemes]]
name = 'gruvbox'
terminal = [
  '#282828', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984',
  '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2',
]
[plugins.colorschemes.highlight]
Visual = { ctermbg = 237, cterm = 'NONE', guibg = '#3c3836', gui = 'NONE' }

[[plugins]]
repo = 'mvanderkamp/cocoa.vim'
[[plugins.colorschemes]]
name = 'cocoa'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins.colorschemes]]
name = 'jellybeans'
terminal = [
  '#151515', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
  '#6b7089', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
]

[[plugins]]
repo = 'phanviet/vim-monokai-pro'
[[plugins.colorschemes]]
name = 'monokai_pro'

[[plugins]]
repo = 'pineapplegiant/spaceduck'
[[plugins.colorschemes]]
name = 'spaceduck'

[[plugins]]
repo = 'rakr/vim-two-firewatch'
[[plugins.colorschemes]]
name = 'two-firewatch'
lightline = 'twofirewatch'

[[plugins]]
repo = 'rakr/vim-one'
[[plugins.colorschemes]]
name = 'one'
terminal = [
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#828997',
  '#5c6370', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#abb2bf',
]

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
[[plugins.colorschemes]]
name = 'spring-night'
lightline = 'spring_night'

[[plugins]]
repo = 'romainl/Apprentice'
[[plugins.colorschemes]]
name = 'apprentice'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
let g:edge_better_performance = v:true
'''
[[plugins.colorschemes]]
name = 'edge'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_better_performance = v:true
'''
[[plugins.colorschemes]]
name = 'gruvbox-material'
lightline = 'gruvbox_material'

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'savq/melange'
[[plugins.colorschemes]]
name = 'melange'
lightline = 'mini'
[plugins.colorschemes.highlight]
CursorLineNr = { cterm = 'NONE' }

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'severij/vadelma'
[[plugins.colorschemes]]
name = 'vadelma'

[[plugins]]
repo = 'sonph/onehalf'
rtp = 'vim'
[[plugins.colorschemes]]
name = 'onehalfdark'
terminal = [
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
]

[[plugins]]
repo = 'srcery-colors/srcery-vim'
[[plugins.colorschemes]]
name = 'srcery'
[plugins.colorscheme.highlight]
Visual = { ctermbg = 236, guibg = '#303030', term = 'NONE', cterm = 'NONE', gui = 'NONE' }

[[plugins]]
repo = 'tomasr/molokai'
[[plugins.colorschemes]]
name = 'molokai'
terminal = [
  '#1b1d1e', '#f92672', '#82b414', '#fd971f', '#268bd2', '#8c54fe', '#56c2d6', '#ccccc6',
  '#505354', '#ff5995', '#b7eb46', '#feed6c', '#62ade3', '#bfa0fe', '#94d8e5', '#f8f8f2',
]

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'
[[plugins.colorschemes]]
name = 'deep-space'
lightline = 'deepspace'

[[plugins]]
repo = 'ulwlu/elly.vim'
[[plugins.colorschemes]]
name = 'elly'

[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins.colorschemes]]
name = 'hybrid'
terminal = [
  '#1d1f21', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#d3d7cf',
  '#707880', '#cc6666', '#b5bd68', '#de955f', '#729fcf', '#b294bb', '#005f5f', '#707880',
]

[[plugins]]
repo = 'wadackel/vim-dogrun'
[[plugins.colorschemes]]
name = 'dogrun'
terminal = [
  '#111219', '#c261b6', '#7cbe8c', '#8e8a6f', '#4c89ac', '#6c75cb', '#73c1a9', '#9ea3c0',
  '#545c8c', '#b871b8', '#7cbe8c', '#a8a384', '#589ec6', '#929be5', '#59b6b6', '#9ea3c0',
]

[[plugins]]
repo = 'whatyouhide/vim-gotham'
[[plugins.colorschemes]]
name = 'gotham'

# NOTE: green and yellow of term ansi color is original
[[plugins]]
repo = 'yuttie/hydrangea-vim'
[[plugins.colorschemes]]
name = 'hydrangea'
terminal = [
  '#1e222c', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#c398fe', '#56c7ee', '#586374',
  '#3b4351', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#fe7ecd', '#56c7ee', '#c3d5ec',
]
[plugins.colorschmes.highlight]
Constant = { ctermbg = 'NONE', guibg = 'NONE' }
Number = { ctermbg = 'NONE', guibg = 'NONE' }
SpecialKey = { ctermbg = 'NONE', guibg = 'NONE' }

# NOTE: maybe it doesn't support lightline.vim expand component
# [[plugins]]
# repo = 'gkapfham/vim-vitamin-onec''
# hook_add = '''
# call user#colorscheme#register('vim-vitamin-onec', {
#       \ 'name': 'vitaminonec',
#       \ })
# '''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'FrenzyExists/aquarium-vim'
[[plugins.colorschemes]]
name = 'aquarium'
[plugins.colorschemes.link]
NonText = 'Comment'

# TODO: it doesn't support terminal ansi colors
# https://github.com/DTr4n/windows-terminal-wombat'
[[plugins]]
repo = 'vim-scripts/wombat256.vim'
[[plugins.colorschemes]]
name = 'wombat256mod'
lightline = 'wombat'
[plugins.colorschemes.link]
NonText = 'Comment'
[plugins.colorschemes.highlight]
CursorLineNr = { cterm = 'NONE' }

# Thank mityu very much!
[[plugins]]
repo = 'https://raw.githubusercontent.com/mityu/dotfiles/master/dot_vim/runtime/colors/reliquiae.vim'
script_type = 'colors'
type = 'raw'
[[plugins.colorschemes]]
name = 'reliquiae'
lightline = 'mini'

# Thank Shougo very much!
# [[plugins]]
# repo = 'https://raw.githubusercontent.com/Shougo/shougo-s-github/master/vim/colors/candy.vim'
# script_type = 'colors'
# type = 'raw'
# hook_add = '''
# call user#colorscheme#register('candy.vim', {
#       \ 'lightline': 'mini',
#       \ })
# '''

# TODO: this plugin is supprting lightline.vim, but I can't enable it because
#       v:lua is only in neovim. I will send the repository pull-request...
# [[plugins]]
# repo = 'EdenEast/nightfox.nvim'
# if = 'has("nvim")'
# hook_add = '''
# call user#colorscheme#register('nightfox.nvim', {}, has('nvim'))
# '''

