
[[plugins]]
repo = '4513echo/vim-colors-hatsunemiku'
hook_add = '''
call user#colorscheme#register('vim-colors-hatsunemiku')
" call user#colorscheme#register('vim-colors-hatsunemiku', 'hatsunemiku_light')
'''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'cormacrelf/vim-colors-github'
hook_add = '''
call user#colorscheme#register('vim-colors-github', {
      \ 'highlight': {
      \   'EndOfBuffer': {
      \     'ctermbg': 'NONE', 'guibg': 'NONE',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'embark-theme/vim'
name = 'embark-theme'
hook_add = '''
call user#colorscheme#register('embark-theme', {
      \ 'name': 'embark',
      \ })
'''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'fcpg/vim-orbital'
hook_add = '''
call user#colorscheme#register('vim-orbital', {
      \ 'highlight': {
      \   'String': {
      \     'ctermbg': 'NONE', 'guibg': 'NONE',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'felipec/vim-felipec'
hook_add = '''
call user#colorscheme#register('vim-felipec', {
      \ 'highlight': {
      \   'NonText': {
      \     'ctermbg': 'NONE', 'guibg': 'NONE',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'KabbAmine/yowish.vim'
hook_add = '''
call user#colorscheme#register('yowish.vim')
let g:yowish = {
      \ 'ctrlp': v:false,
      \ 'unite': v:false,
      \ 'nerdtree': v:false,
      \ 'agit': v:false,
      \ 'signjk': v:false,
      \ }
'''

[[plugins]]
repo = 'Rigellute/rigel'
hook_add = '''
call user#colorscheme#register('rigel')
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
call user#colorscheme#register('nord-vim')
'''

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
call user#colorscheme#register('ayu-vim')
'''

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
hook_add = '''
call user#colorscheme#register('vim-nightfly-guicolors', {
      \ 'name': 'nightfly',
      \ })
'''

[[plugins]]
repo = 'challenger-deep-theme/vim'
name = 'challenger-deep-theme'
hook_add = '''
call user#colorscheme#register('challenger-deep-theme', {
      \ 'name': 'challenger_deep',
      \ })
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
call user#colorscheme#register('iceberg.vim', {
      \ 'highlight': {
      \   'String': {
      \     'ctermfg': 144, 'guifg': '#a7b1a9',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'connorholyday/vim-snazzy'
hook_add = '''
call user#colorscheme#register('vim-snazzy', {
      \ 'highlight': {
      \   'Visual': {
      \     'ctermbg': 254, 'guibg': '#e4e4ee',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
hook_add = '''
call user#colorscheme#register('dracula')
'''

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'
hook_add = '''
call user#colorscheme#register('palenight.vim')
'''

[[plugins]]
repo = 'fenetikm/falcon'
hook_add = '''
call user#colorscheme#register('falcon')
'''

[[plugins]]
repo = 'franbach/miramare'
hook_add = '''
call user#colorscheme#register('miramare')
'''

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
hook_add = '''
call user#colorscheme#register('tokyonight-vim')
'''

[[plugins]]
repo = 'habamax/vim-gruvbit'
hook_add = '''
call user#colorscheme#register('vim-gruvbit')
'''

[[plugins]]
repo = 'haishanh/night-owl.vim'
hook_add = '''
call user#colorscheme#register('night-owl.vim', {
      \ 'lightline': 'nightowl',
      \ })
'''

[[plugins]]
repo = 'haystackandroid/snow'
hook_add = '''
call user#colorscheme#register('snow', {
      \ 'lightline': 'snow_dark',
      \ })
'''

[[plugins]]
repo = 'haystackandroid/stellarized'
hook_add = '''
call user#colorscheme#register('stellarized', {
      \ 'lightline': 'stellarized_dark',
      \ })
'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
call user#colorscheme#register('tender.vim')
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
call user#colorscheme#register('onedark.vim')
'''

[[plugins]]
repo = 'karoliskoncevicius/sacredforest-vim'
hook_add = '''
call user#colorscheme#register('sacredforest-vim')
'''

[[plugins]]
repo = 'kyoh86/momiji'
hook_add = '''
call user#colorscheme#register('momiji')
'''

[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
call user#colorscheme#register('vim-solarized8', {
      \ 'lightline': 'solarized',
      \ })
'''

[[plugins]]
repo = 'lighthaus-theme/vim-lighthaus'
hook_add = '''
call user#colorscheme#register('vim-lighthaus')
'''

[[plugins]]
repo = 'mhartington/oceanic-next'
hook_add = '''
call user#colorscheme#register('oceanic-next', {
      \ 'name': 'OceanicNext',
      \ 'lightline': 'oceanicnext',
      \ })
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
call user#colorscheme#register('gruvbox', {
      \ 'highlight': {
      \   'Visual': {
      \     'ctermbg': 237, 'cterm': 'NONE', 'guibg': '#3c3836', 'gui': 'NONE',
      \   },
      \ },
      \ 'terminal': [
      \   '#282828', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984',
      \   '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2',
      \ ],
      \ })
'''

[[plugins]]
repo = 'mvanderkamp/cocoa.vim'
hook_add = '''
call user#colorscheme#register('cocoa.vim')
'''

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
call user#colorscheme#register('jellybeans.vim', {
      \ 'terminal': [
      \   '#151515', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
      \   '#6b7089', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
      \ ],
      \ })
'''

[[plugins]]
repo = 'phanviet/vim-monokai-pro'
hook_add = '''
call user#colorscheme#register('vim-monokai-pro', {
      \ 'name': 'monokai_pro',
      \ })
'''

[[plugins]]
repo = 'pineapplegiant/spaceduck'
hook_add = '''
call user#colorscheme#register('spaceduck')
'''

[[plugins]]
repo = 'rakr/vim-two-firewatch'
hook_add = '''
call user#colorscheme#register('vim-two-firewatch', {
      \ 'lightline': 'twofirewatch',
      \ })
'''

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
call user#colorscheme#register('vim-one', {
      \ 'terminal': [
      \   '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#828997',
      \   '#5c6370', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#abb2bf',
      \ ],
      \ })
'''

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
hook_add = '''
call user#colorscheme#register('vim-color-spring-night', {
      \ 'lightline': 'spring_night',
      \ })
'''

[[plugins]]
repo = 'romainl/Apprentice'
hook_add = '''
call user#colorscheme#register('Apprentice', {
      \ 'name': 'apprentice',
      \ })
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
let g:edge_better_performance = v:true
call user#colorscheme#register('edge')
'''

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_better_performance = v:true
call user#colorscheme#register('gruvbox-material', {
      \ 'lightline': 'gruvbox_material',
      \ })
'''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'savq/melange'
hook_add = '''
call user#colorscheme#register('melange', {
      \ 'lightline': 'mini',
      \ 'highlight': {
      \   'CursorLineNr': {
      \     'cterm': 'NONE',
      \   },
      \ },
      \ })
'''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'severij/vadelma'
hook_add = '''
call user#colorscheme#register('vadelma')
'''

[[plugins]]
repo = 'sonph/onehalf'
rtp = 'vim'
hook_add = '''
call user#colorscheme#register('onehalf', {
      \ 'name': 'onehalfdark',
      \ 'terminal': [
      \   '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
      \   '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
      \ ],
      \ })
'''

[[plugins]]
repo = 'srcery-colors/srcery-vim'
hook_add = '''
call user#colorscheme#register('srcery-vim', {
      \ 'highlight': {
      \   'Visual': {
      \     'ctermbg': 236, 'guibg': '#303030',
      \     'term': 'NONE', 'cterm': 'NONE', 'gui': 'NONE',
      \   },
      \ },
      \ })
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
call user#colorscheme#register('molokai', {
      \ 'terminal': [
      \   '#1b1d1e', '#f92672', '#82b414', '#fd971f', '#268bd2', '#8c54fe', '#56c2d6', '#ccccc6',
      \   '#505354', '#ff5995', '#b7eb46', '#feed6c', '#62ade3', '#bfa0fe', '#94d8e5', '#f8f8f2',
      \ ],
      \ })
'''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'
hook_add = '''
call user#colorscheme#register('vim-deep-space', {
      \ 'lightline': 'deepspace',
      \ })
'''

[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
call user#colorscheme#register('elly.vim')
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
call user#colorscheme#register('vim-hybrid', {
      \ 'terminal': [
      \   '#1d1f21', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#d3d7cf',
      \   '#707880', '#cc6666', '#b5bd68', '#de955f', '#729fcf', '#b294bb', '#005f5f', '#707880',
      \ ],
      \ })
'''

[[plugins]]
repo = 'wadackel/vim-dogrun'
hook_add = '''
call user#colorscheme#register('vim-dogrun', {
      \ 'terminal': [
      \   '#111219', '#c261b6', '#7cbe8c', '#8e8a6f', '#4c89ac', '#6c75cb', '#73c1a9', '#9ea3c0',
      \   '#545c8c', '#b871b8', '#7cbe8c', '#a8a384', '#589ec6', '#929be5', '#59b6b6', '#9ea3c0',
      \ ],
      \ })
'''

[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = '''
call user#colorscheme#register('vim-gotham')
'''

# NOTE: green and yellow of term ansi color is original
[[plugins]]
repo = 'yuttie/hydrangea-vim'
hook_add = '''
call user#colorscheme#register('hydrangea-vim', {
      \ 'highlight': {
      \   'Constant': { 'ctermbg': 'NONE', 'guibg': 'NONE' },
      \   'Number': { 'ctermbg': 'NONE', 'guibg': 'NONE' },
      \   'SpecialKey': { 'ctermbg': 'NONE', 'guibg': 'NONE' },
      \ },
      \ 'terminal': [
      \   '#1e222c', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#c398fe', '#56c7ee', '#586374',
      \   '#3b4351', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#fe7ecd', '#56c7ee', '#c3d5ec',
      \ ],
      \ })
'''

# NOTE: maybe it doesn't support lightline.vim expand component
# [[plugins]]
# repo = 'gkapfham/vim-vitamin-onec''
# hook_add = '''
# call user#colorscheme#register('vim-vitamin-onec', {
#       \ 'name': 'vitaminonec',
#       \ })
# '''

# TODO: it doesn't support terminal ansi colors
[[plugins]]
repo = 'FrenzyExists/aquarium-vim'
hook_add = '''
call user#colorscheme#register('aquarium-vim', {
      \ 'link': {
      \   'NonText': 'Comment',
      \ },
      \ })
'''

# TODO: it doesn't support terminal ansi colors
# https://github.com/DTr4n/windows-terminal-wombat'
[[plugins]]
repo = 'vim-scripts/wombat256.vim'
hook_add = '''
call user#colorscheme#register('wombat256.vim', {
      \ 'name': 'wombat256mod',
      \ 'lightline': 'wombat',
      \ 'link': {
      \   'NonText': 'Comment',
      \ },
      \ 'highlight': {
      \   'CursorLineNr': { 'cterm': 'NONE' },
      \ },
      \ })
'''

# Thank mityu very much!
[[plugins]]
repo = 'https://raw.githubusercontent.com/mityu/dotfiles/master/dot_vim/runtime/colors/reliquiae.vim'
script_type = 'colors'
type = 'raw'
hook_add = '''
call user#colorscheme#register('reliquiae.vim', {
      \ 'lightline': 'mini',
      \ })
'''

# Thank Shougo very much!
# [[plugins]]
# repo = 'https://raw.githubusercontent.com/Shougo/shougo-s-github/master/vim/colors/candy.vim'
# script_type = 'colors'
# type = 'raw'
# hook_add = '''
# call user#colorscheme#register('candy.vim', {
#       \ 'lightline': 'mini',
#       \ })
# '''

# TODO: this plugin is supprting lightline.vim, but I can't enable it because
#       v:lua is only in neovim. I will send the repository pull-request...
# [[plugins]]
# repo = 'EdenEast/nightfox.nvim'
# if = 'has("nvim")'
# hook_add = '''
# call user#colorscheme#register('nightfox.nvim', {}, has('nvim'))
# '''

