
[[plugins]]
repo = '4513echo/vim-colors-hatsunemiku'
[[plugins.colorschemes]]
name = 'hatsunemiku'
# [[plugins.colorschemes]]
# name = 'hatsunemiku_light'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
[[plugins.colorschemes]]
name = 'nord'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
[[plugins.colorschemes]]
name = 'ayu'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignDelete = { ctermfg = 12, ctermbg = 6, guifg = '#0000ff', guibg = '#008080' }

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'
[[plugins.colorschemes]]
name = 'nightfly'

[[plugins]]
repo = 'challenger-deep-theme/vim'
name = 'challenger-deep-theme'
[[plugins.colorschemes]]
name = 'challenger_deep'

[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins.colorschemes]]
name = 'iceberg'
[plugins.colorschemes.highlight]
String = { ctermfg = 144, guifg = '#a7b1a9' }

[[plugins]]
repo = 'connorholyday/vim-snazzy'
[[plugins.colorschemes]]
name = 'snazzy'

[[plugins]]
repo = 'cormacrelf/vim-colors-github'
[[plugins.colorschemes]]
name = 'github'
[plugins.colorschemes.highlight]
EndOfBuffer = { ctermfg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
[[plugins.colorschemes]]
name = 'dracula'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'
[[plugins.colorschemes]]
name = 'palenight'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins.colorschemes]]
name = 'nightfox'
[[plugins.colorschemes]]
name = 'duskfox'
[[plugins.colorschemes]]
name = 'nordfox'
[[plugins.colorschemes]]
name = 'terafox'
# [[plugins.colorschemes]]
# name = 'dawnfox'
# [[plugins.colorschemes]]
# name = 'dayfox'

[[plugins]]
repo = 'embark-theme/vim'
name = 'embark-theme'
[[plugins.colorschemes]]
name = 'embark'

[[plugins]]
repo = 'fcpg/vim-orbital'
[[plugins.colorschemes]]
name = 'orbital'
terminal = 'mini'
[plugins.colorschemes.highlight]
String = { ctermbg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'felipec/vim-felipec'
[[plugins.colorschemes]]
name = 'felipec'
[plugins.colorschemes.highlight]
NonText = { ctermbg = 'NONE', guibg = 'NONE' }

[[plugins]]
repo = 'fenetikm/falcon'
[[plugins.colorschemes]]
name = 'falcon'

[[plugins]]
repo = 'franbach/miramare'
[[plugins.colorschemes]]
name = 'miramare'

[[plugins]]
repo = 'FrenzyExists/aquarium-vim'
[[plugins.colorschemes]]
name = 'aquarium'
terminal = 'mini'
[plugins.colorschemes.link]
NonText = 'Comment'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignDelete = { ctermfg = 12, ctermbg = 6, guifg = '#ebb9b9', guibg = '#20202a' }

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'
[[plugins.colorschemes]]
name = 'tokyonight'

[[plugins]]
repo = 'gkapfham/vim-vitamin-onec'
[[plugins.colorschemes]]
name = 'vitaminonec'
lightline = 'mini'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignAdd = { ctermfg = 64, ctermbg = 234, guifg = '#5f8700', guibg = '#1c1c1d' }
SignifySignChange = { ctermfg = 110, ctermbg = 234, guifg = '#87afd7', guibg = '#1c1c1d' }
SignifySignDelete = { ctermfg = 167, ctermbg = 234, guifg = '#d75f5f', guibg = '#1c1c1d' }

[[plugins]]
repo = 'habamax/vim-gruvbit'
[[plugins.colorschemes]]
name = 'gruvbit'

[[plugins]]
repo = 'haishanh/night-owl.vim'
[[plugins.colorschemes]]
name = 'night-owl'
lightline = 'nightowl'

[[plugins]]
repo = 'haystackandroid/snow'
[[plugins.colorschemes]]
name = 'snow'
lightline = 'snow_dark'

[[plugins]]
repo = 'haystackandroid/stellarized'
[[plugins.colorschemes]]
name = 'stellarized'
lightline = 'stellarized_dark'

[[plugins]]
repo = 'haxibami/urara.vim'
[[plugins.colorschemes]]
name = 'urara'

# Thank mityu very much!
[[plugins]]
repo = 'https://raw.githubusercontent.com/mityu/dotfiles/master/dot_vim/runtime/colors/reliquiae.vim'
script_type = 'colors'
type = 'raw'
[[plugins.colorschemes]]
name = 'reliquiae'
lightline = 'mini'

# Thank Shougo very much!
[[plugins]]
repo = 'https://raw.githubusercontent.com/Shougo/shougo-s-github/master/vim/colors/candy.vim'
script_type = 'colors'
type = 'raw'
[[plugins.colorschemes]]
name = 'candy'
lightline = 'mini'
terminal = 'mini'

[[plugins]]
repo = 'jacoborus/tender.vim'
[[plugins.colorschemes]]
name = 'tender'

[[plugins]]
repo = 'joshdick/onedark.vim'
[[plugins.colorschemes]]
name = 'onedark'

[[plugins]]
repo = 'KabbAmine/yowish.vim'
[[plugins.colorschemes]]
name = 'yowish'
terminal = 'mini'
[plugins.colorschemes.link]
Directory = 'Statement'

[[plugins]]
repo = 'karoliskoncevicius/sacredforest-vim'
[[plugins.colorschemes]]
name = 'sacredforest'

[[plugins]]
repo = 'kyoh86/momiji'
[[plugins.colorschemes]]
name = 'momiji'

[[plugins]]
repo = 'lifepillar/vim-solarized8'
[[plugins.colorschemes]]
name = 'solarized8'
lightline = 'solarized'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignDelete = { ctermfg = 160, ctermbg = 236, guifg = '#dc322f', guibg = '#073642' }

[[plugins]]
repo = 'lighthaus-theme/vim-lighthaus'
[[plugins.colorschemes]]
name = 'lighthaus'

[[plugins]]
repo = 'mhartington/oceanic-next'
[[plugins.colorschemes]]
name =  'OceanicNext'
lightline = 'oceanicnext'

[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins.colorschemes]]
name = 'gruvbox'
terminal = [
  '#282828', '#cc241d', '#98971a', '#d79921', '#458588', '#b16286', '#689d6a', '#a89984',
  '#928374', '#fb4934', '#b8bb26', '#fabd2f', '#83a598', '#d3869b', '#8ec07c', '#ebdbb2',
]
[plugins.colorschemes.highlight]
Visual = { ctermbg = 237, cterm = 'NONE', guibg = '#3c3836', gui = 'NONE' }

[[plugins]]
repo = 'mvanderkamp/cocoa.vim'
[[plugins.colorschemes]]
name = 'cocoa'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
[[plugins.colorschemes]]
name = 'jellybeans'
terminal = [
  '#151515', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
  '#6b7089', '#cf6a4c', '#70b950', '#fad07a', '#8fbfdc', '#c6b6ee', '#89b8c2', '#e8e8d3',
]

[[plugins]]
repo = 'phanviet/vim-monokai-pro'
[[plugins.colorschemes]]
name = 'monokai_pro'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignAdd = { ctermfg = 231, ctermbg = 64, guifg = '#fcfcfa', guibg = '#47840e' }
SignifySignDelete = { ctermfg = 88, guifg = '#8c0809' }
SignifySignChange = { ctermfg = 231, ctermbg = 23, guifg = '#fcfcfa', guibg = '#273a5b' }

[[plugins]]
repo = 'pineapplegiant/spaceduck'
[[plugins.colorschemes]]
name = 'spaceduck'

[[plugins]]
repo = 'rakr/vim-two-firewatch'
[[plugins.colorschemes]]
name = 'two-firewatch'
lightline = 'twofirewatch'

[[plugins]]
repo = 'rakr/vim-one'
[[plugins.colorschemes]]
name = 'one'
terminal = [
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#828997',
  '#5c6370', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#abb2bf',
]

[[plugins]]
repo = 'rhysd/vim-color-spring-night'
[[plugins.colorschemes]]
name = 'spring-night'
lightline = 'spring_night'

[[plugins]]
repo = 'Rigellute/rigel'
[[plugins.colorschemes]]
name = 'rigel'
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignChange = { ctermfg = 44, ctermbg = 235, guifg = '#00cccc', guibg = '#002635' }

[[plugins]]
repo = 'romainl/Apprentice'
[[plugins.colorschemes]]
name = 'apprentice'

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
let g:edge_better_performance = v:true
'''
[[plugins.colorschemes]]
name = 'edge'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = '''
let g:gruvbox_material_better_performance = v:true
'''
[[plugins.colorschemes]]
name = 'gruvbox-material'
lightline = 'gruvbox_material'

[[plugins]]
repo = 'savq/melange'
[[plugins.colorschemes]]
name = 'melange'
lightline = 'mini'
terminal = 'mini'
[plugins.colorschemes.highlight]
CursorLineNr = { cterm = 'NONE' }

[[plugins]]
repo = 'severij/vadelma'
[[plugins.colorschemes]]
name = 'vadelma'
terminal = 'mini'

[[plugins]]
repo = 'sonph/onehalf'
rtp = 'vim'
[[plugins.colorschemes]]
name = 'onehalfdark'
terminal = [
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
  '#282c34', '#e06c75', '#98c379', '#e5c07b', '#61afef', '#c678dd', '#56b6c2', '#dcdfe4',
]

[[plugins]]
repo = 'srcery-colors/srcery-vim'
[[plugins.colorschemes]]
name = 'srcery'
[plugins.colorschemes.highlight]
Visual = { ctermbg = 236, guibg = '#303030', term = 'NONE', cterm = 'NONE', gui = 'NONE' }

[[plugins]]
repo = 'tobi-wan-kenobi/zengarden'
[[plugins.colorschemes]]
name = 'zengarden'

[[plugins]]
repo = 'tomasr/molokai'
[[plugins.colorschemes]]
name = 'molokai'
terminal = [
  '#1b1d1e', '#f92672', '#82b414', '#fd971f', '#268bd2', '#8c54fe', '#56c2d6', '#ccccc6',
  '#505354', '#ff5995', '#b7eb46', '#feed6c', '#62ade3', '#bfa0fe', '#94d8e5', '#f8f8f2',
]
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignDelete = { ctermfg = 162, ctermbg = 5, guifg = '#960050', guibg = '#1e0010' }

[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'
[[plugins.colorschemes]]
name = 'deep-space'
lightline = 'deepspace'
terminal = 'mini'

[[plugins]]
repo = 'ulwlu/elly.vim'
[[plugins.colorschemes]]
name = 'elly'

# TODO: try https://github.com/DTr4n/windows-terminal-wombat'
[[plugins]]
repo = 'vim-scripts/wombat256.vim'
[[plugins.colorschemes]]
name = 'wombat256mod'
lightline = 'wombat'
terminal = 'mini'
[plugins.colorschemes.link]
NonText = 'Comment'
[plugins.colorschemes.highlight]
CursorLineNr = { cterm = 'NONE' }

[[plugins]]
repo = 'w0ng/vim-hybrid'
[[plugins.colorschemes]]
name = 'hybrid'
terminal = [
  '#1d1f21', '#cc6666', '#b5bd68', '#f0c674', '#81a2be', '#b294bb', '#8abeb7', '#d3d7cf',
  '#707880', '#cc6666', '#b5bd68', '#de955f', '#729fcf', '#b294bb', '#005f5f', '#707880',
]

[[plugins]]
repo = 'wadackel/vim-dogrun'
[[plugins.colorschemes]]
name = 'dogrun'
terminal = [
  '#111219', '#c261b6', '#7cbe8c', '#8e8a6f', '#4c89ac', '#6c75cb', '#73c1a9', '#9ea3c0',
  '#545c8c', '#b871b8', '#7cbe8c', '#a8a384', '#589ec6', '#929be5', '#59b6b6', '#9ea3c0',
]
[plugins.colorschemes.highlight]
# NOTE: Remove term/cterm/gui attrs
SignifySignAdd = { ctermbg = 237, guibg = '#1c394b' }
SignifySignChange = { ctermbg = 23, guibg = '#26463b' }
SignifySignDelete = { ctermfg = 189, ctermbg = 96, guifg = '#d2d9ff', guibg = '#5e3e5e' }

[[plugins]]
repo = 'whatyouhide/vim-gotham'
[[plugins.colorschemes]]
name = 'gotham'

# NOTE: green and yellow of term ansi color is original
[[plugins]]
repo = 'yuttie/hydrangea-vim'
[[plugins.colorschemes]]
name = 'hydrangea'
terminal = [
  '#1e222c', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#c398fe', '#56c7ee', '#586374',
  '#3b4351', '#e91e63', '#9df086', '#fedc1b', '#537dd5', '#fe7ecd', '#56c7ee', '#c3d5ec',
]
[plugins.colorschemes.highlight]
Constant = { ctermbg = 'NONE', guibg = 'NONE' }
Number = { ctermbg = 'NONE', guibg = 'NONE' }
SpecialKey = { ctermbg = 'NONE', guibg = 'NONE' }

