[[plugins]]
repo = 'https://github.com/Shougo/ddu.vim'
depends = ['denops.vim']
on_func = ['ddu#start']
hooks_file = '$DEIN_DIR/settings/ddu.vim'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-commands.vim'
depends = ['ddu.vim']
on_cmd = ['Ddu']

# UI

[[plugins]]
repo = 'https://github.com/Shougo/cmdline.vim'
on_ft = ['ddu-ff']
hook_source = '''
function! s:cmdline_set_option()
  call cmdline#set_option(#{
        \ border: 'rounded',
        \ col: &columns / 6,
        \ row: &lines / 6 - 3,
        \ highlight_border: 'Identifier',
        \ width: &columns / 3 * 2,
        \ })
endfunction
autocmd vimrc VimResized * call s:cmdline_set_option()
call s:cmdline_set_option()
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-ui-ff'

# filters

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-matcher_hidden'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-matcher_relative'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'https://github.com/yuki-yano/ddu-filter-fzf'

# kinds

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-kind-url'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-kind-file'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-kind-word'

# sources

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-source-colorscheme'

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-source-emoji'

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-source-ghq'

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-source-pypi_classifiers'

[[plugins]]
repo = 'https://github.com/4513ECHO/ddu-source-source'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_status'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-mr'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-tags'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-action'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-line'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-register'

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-dein_update'

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-file_external'

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-command_history'

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-help'

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-man'

[[plugins]]
repo = 'https://github.com/shun/ddu-source-buffer'

[[plugins]]
repo = 'https://github.com/shun/ddu-source-rg'

[[plugins]]
repo = 'https://github.com/uga-rosa/ddu-source-lsp'

[[plugins]]
repo = 'https://github.com/yuki-yano/ddu-source-nvim-notify'
