hook_add = '''
let g:python_highlight_all = v:true
let g:awk_is_gawk = v:true
let g:is_bash = v:true
let g:rust_bang_comment_leader = v:true
let g:markdown_fenced_languages = ['ts=typescript']
let g:vim_indent_cont = 6
'''

[ftplugin]
_ = '''
setlocal formatoptions-=ro
setlocal formatoptions+=mMBl
'''

dockerfile = '''
function! s:set_abbrev(instruction) abort
  execute 'inoreabbrev <expr><buffer>' a:instruction
        \ printf("(getline('.')[:col('.') - 2] ==# '%s')", a:instruction)
        \ printf("? '%s' : '%s'", toupper(a:instruction), a:instruction)
endfunction

call s:set_abbrev('add')
call s:set_abbrev('cmd')
call s:set_abbrev('copy')
call s:set_abbrev('entrypoint')
call s:set_abbrev('env')
call s:set_abbrev('expose')
call s:set_abbrev('from')
call s:set_abbrev('healthcheck')
call s:set_abbrev('label')
call s:set_abbrev('onbuild')
call s:set_abbrev('run')
call s:set_abbrev('shell')
call s:set_abbrev('user')
call s:set_abbrev('volume')
call s:set_abbrev('workdir')

inoreabbrev <expr><buffer> as
      \ (getline('.')[:col('.') - 2] =~# '^FROM\s\+.*\s\+') ? 'AS' : 'as'
'''

gitcommit = '''
" from https://zenn.dev/uochan/articles/2021-12-08-vim-conventional-commits
function! s:select_type() abort
  let title = printf('%s: ', trim(split(getline('.'), ';')[0]))

  silent! normal! "_dip
  silent! put! =title
  silent! startinsert!
endfunction
nnoremap <buffer> <CR><CR> <Cmd>call <SID>select_type()<CR>
'''

gitrebase = '''
nnoremap <buffer> <CR> <Cmd>Cycle<CR>
'''

help = '''
setlocal iskeyword+=#
setlocal iskeyword+=:
setlocal iskeyword+=-
setlocal iskeyword+=+

nnoremap <buffer> q <C-w>q
nnoremap <buffer> <CR> <C-]>zv
xnoremap <buffer> <CR> <C-]>zv
nnoremap <buffer><silent><expr> [Toggle]l
      \ expand('%:e') ==# 'jax'
      \ ? printf('<Cmd>help %s@en<CR>', expand('<cword>'))
      \ : printf('<Cmd>help %s@ja<CR>', expand('<cword>'))

let s:tag_pattern = join([
      \ '\\\@<!|[#-)!+-~]\+|', '\*[#-)!+-~]\+\*\s', '\*[#-)!+-~]\+\*$',
      \ "'[a-z]\\{2,\\}'", "'t_..'",
      \ '<[-a-zA-Z0-9_]\+>', '<[SCM]-.>',
      \ 'CTRL-.', 'CTRL-SHIFT-.', 'CTRL-Break', 'CTRL-PageUp', 'CTRL-PageDown',
      \ 'CTRL-Insert', 'CTRL-Del', 'CTRL-{char}',
      \ ], '\|')
function! s:move_link(dir) abort
  call search(s:tag_pattern, a:dir ? 'sW' : 'bsW', 0, 500)
endfunction
nnoremap <buffer> <C-n> <Cmd>call <SID>move_link(1)<CR>
nnoremap <buffer> <C-p> <Cmd>call <SID>move_link(0)<CR>
'''

markdown = '''
hi link markdownCode Constant
autocmd vimrc ColorScheme *
      \ hi link markdownCode Constant
'''

python = '''
setlocal softtabstop=4
setlocal shiftwidth=4
setlocal textwidth=80
setlocal smarttab
setlocal nosmartindent
inoreabbrev <expr><buffer> improt
      \ (getline('.')[:col('.') - 2] =~# 'from\s\+.*\s\+' <Bar><Bar>
      \  getline('.')[:col('.') - 2] ==# 'improt')
      \ ? 'import' : 'improt'
'''

qf = '''
setlocal nowrap
setlocal numberwidth=2
nnoremap <buffer> q <Cmd>cclose<CR>
nnoremap <buffer><expr> j line('.') == line('$') ? 'gg' : 'j'
nnoremap <buffer><expr> k line('.') == 1 ? 'K' : 'k'
" from https://github.com/mityu/dotfiles/blob/f5cb5f9a92/dot_vim/runtime/ftplugin/qf.vim#L6
nnoremap <buffer> o <CR>zz<C-w>p
nnoremap <buffer> p <CR>zz<C-w>p
" from https://github.com/kuuote/dotvim/blob/9c7ba6307c/ftplugin/qf.vim#L1
nnoremap <buffer> j j <CR>zz<C-w>b
nnoremap <buffer> k k <CR>zz<C-w>b
'''

toml = '''
if !has('nvim') && !empty(filter(getline(1, 4),
      \ { _, val -> val =~# '\V\^\([[plugins]]\|hook_\)' }))
  call dein#toml#syntax()
endif
'''

zsh = '''
setlocal iskeyword+=-
'''

# [[plugins]]
# repo = 'jparise/vim-graphql'
# repo = '4513echo/vim-graphql'
# rev = 'typescript-comment'
# on_ft = ['graphql', 'typescript', 'typescriptreact']

[[plugins]]
repo = 'bfrg/vim-jq'
merge_ftdetect = true
on_ft = ['jq']

[[plugins]]
repo = 'cespare/vim-toml'
if = '!has("patch-8.2.3520") && !has("nvim")'
merge_ftdetect = true
on_ft = ['toml']

[[plugins]]
repo = 'cohama/vim-hier'
on_ft = ['qf']
on_cmd = ['HierClean', 'HierStart', 'HierStop', 'HierUpdate']
[plugins.ftplugin]
qf = '''
autocmd vimrc WinClosed <buffer>
      \ : if &buftype ==# 'quickfix'
      \ |   execute 'HierStop'
      \ | endif
'''

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['vim', 'css', 'scss', 'sass']

[[plugins]]
repo = 'lark-parser/vim-lark-syntax'
merge_ftdetect = true
on_ft = ['lark']

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = ['markdown']
on_cmd = ['MakeTable', 'UnmakeTable']

[[plugins]]
repo = 'MTDL9/vim-log-highlighting'
merge_ftdetect = true
on_ft = ['log']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_no_default_key_mappings = v:true
let g:vim_markdown_follow_anchor = v:true
let g:vim_markdown_no_extensions_in_markdown = v:true
let g:vim_markdown_math = v:true
let g:vim_markdown_frontmatter = v:true
let g:vim_markdown_strikethrough = v:true
'''

[[plugins]]
repo = 'rbtnn/vim-vimscript_indentexpr'
on_ft = ['vim']

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['markdown']
[plugins.ftplugin]
markdown = '''
syn cluster mkdNonListItem add=@githubFlavoredMarkdown
syn cluster mkdNonListItemBlock add=@githubFlavoredMarkdown
syn cluster githubFlavoredMarkdown contains=githubFlavoredMarkdownCode,
      \githubFlavoredMarkdownMention,githubFlavoredMarkdownStrikethrough,
      \githubFlavoredMarkdownEmoji,githubFlavoredMarkdownTableDelimiter,
      \githubFlavoredMarkdownTableAligner,githubFlavoredMarkdownTableBorder,
      \githubFlavoredMarkdownIssueNumber,githubFlavoredMarkdownCheckBoxBracket,
      \githubFlavoredMarkdownCheckBoxX
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['qf']
on_cmd = ['Qfreplace']
[plugins.ftplugin]
qf = '''
nnoremap <buffer> r <Cmd>Qfreplace<CR>
'''
qfreplace = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
merge_ftdetect = true
on_ft = ['tmux']

[[plugins]]
repo = 'tpope/vim-git'
merge_ftdetect = true
on_ft = ['gitcommit', 'gitconfig', 'gitrebase', 'gitsendmail']

[[plugins]]
repo = 'vim-jp/syntax-vim-ex'
on_ft = ['vim']


