[[plugins]]
repo = 'hrsh7th/nvim-pasta'
on_lua = ['pasta.mappings', 'pasta']
hook_add = '''
lua require('vimrc.plugin.pasta').hook_add()
'''
hook_source = '''
lua require('vimrc.plugin.pasta').hook_source()
'''

[[plugins]]
repo = 'ii14/emmylua-nvim'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
lazy = true
on_lua = ['hlslens']
hook_add = '''
lua require('vimrc.plugin.hlslens').hook_add()
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lazy = true
depends = ['playground']
on_event = ['BufRead']
hook_post_update = 'TSUpdate'
hook_source = '''
lua require('vimrc.plugin.treesitter')
'''
[plugins.ftplugin]
tsplayground = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
lazy = true

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
lazy = true
on_lua = ['scrollbar', 'scrollbar.utils', 'scrollbar.handlers']
hook_add = '''
lua require('vimrc.plugin.scrollbar').hook_add()
'''
hook_source = '''
lua require('vimrc.plugin.scrollbar').hook_source()
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lazy = true
on_lua = ['notify']
hook_source = '''
lua require('vimrc.plugin.notify')
'''

