[[plugins]]
repo = 'hrsh7th/nvim-pasta'
lua_add = '''
vim.keymap.set({ "n", "x" }, "p", require("pasta.mappings").p)
vim.keymap.set({ "n", "x" }, "P", require("pasta.mappings").P)
require("pasta").setup {
  converters = {
    require("pasta.converters").indentation,
  },
  paste_mode = true,
  next_key = vim.api.nvim_replace_termcodes("<C-p>", true, true, true),
  prev_key = vim.api.nvim_replace_termcodes("<C-n>", true, true, true),
}
'''

[[plugins]]
repo = 'ii14/emmylua-nvim'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
lazy = true
on_lua = ['hlslens']
lua_add = '''
require('vimrc.plugin.hlslens').hook_add()
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lazy = true
on_event = ['BufRead']
hook_post_update = 'TSUpdate'
lua_source = '''
require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "bash",
    "go",
    "html",
    "jsdoc",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "rust",
    "toml",
    "typescript",
    "vim",
    "yaml",
  },
  additionnal_vim_regex_highlighting = false,
  highlight = {
    enable = true,
    disable = { "bash", "yaml", "help" },
  },
  playground = {
    enable = true,
    keybindings = {
      update = "<C-r>",
    },
  },
  query_linter = {
    enable = true,
  },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
lazy = true
on_source = ['nvim-treesitter']
[plugins.ftplugin]
tsplayground = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
lazy = true
on_lua = ['scrollbar', 'scrollbar.utils', 'scrollbar.handlers']
lua_add = '''
require('vimrc.plugin.scrollbar').hook_add()
'''
lua_source = '''
require('vimrc.plugin.scrollbar').hook_source()
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lazy = true
on_lua = ['notify']
lua_source = '''
require('vimrc.plugin.notify')
'''

