[[plugins]]
repo = 'hrsh7th/nvim-pasta'
on_lua = 'pasta'
lua_add = '''
vim.keymap.set({ "n", "x" }, "p", function() require("pasta.mappings").p() end)
vim.keymap.set({ "n", "x" }, "P", function() require("pasta.mappings").P() end)
'''
lua_source = '''
require("pasta").setup {
  converters = {
    require("pasta.converters").indentation,
  },
  paste_mode = true,
  next_key = vim.api.nvim_replace_termcodes("<C-p>", true, true, true),
  prev_key = vim.api.nvim_replace_termcodes("<C-n>", true, true, true),
}
require("pasta").setup.filetype({ "markdown", "yaml" }, {
  converters = {},
})
'''

[[plugins]]
repo = 'ii14/emmylua-nvim'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
lazy = true
on_lua = ['hlslens']
on_event = ['CmdlineEnter']
lua_add = '''
require('vimrc.plugin.hlslens').hook_add()
'''
lua_source = '''
require("hlslens").setup { auto_enable = false }
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
lazy = true
on_event = ['BufRead']
hook_post_update = 'TSUpdate'
lua_source = '''
require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "bash",
    "go",
    "html",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "rust",
    "toml",
    "typescript",
    "vim",
    "yaml",
  },
  additionnal_vim_regex_highlighting = false,
  highlight = {
    enable = true,
    disable = { "bash", "yaml", "help" },
  },
  playground = {
    enable = true,
    keybindings = {
      update = "<C-r>",
    },
  },
  query_linter = {
    enable = true,
  },
}
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
lazy = true
on_source = ['nvim-treesitter']
[plugins.ftplugin]
tsplayground = '''
nnoremap <buffer> q <C-w>q
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
lazy = true
on_cmd = ['Notifications']
on_lua = ['notify']
lua_add = '''
vim.notify = function(...) require "notify" (...) end
'''
lua_source = '''
require("notify").setup {
  stages = "slide",
  background_color = "NormalFloat",
  minimum_width = 30,
  icons = {
    ERROR = "✗",
    WARN = "‼",
    INFO = "i",
    DEBUG = "D",
    TRACE = "T",
  },
}
'''

