[[plugins]]
repo = 'https://github.com/cocopon/colorswatch.vim'
on_cmd = ['ColorSwatchGenerate']

[[plugins]]
repo = 'https://github.com/cocopon/inspecthi.vim'
depends = ['colorswatch.vim']
on_cmd = ['Inspecthi']

[[plugins]]
repo = 'https://github.com/machakann/vim-highlightedyank'
on_event = ['TextYankPost']
hook_add = '''
let g:highlightedyank_highlight_duration = 100
'''

[[plugins]]
repo = 'https://github.com/markonm/traces.vim'
on_event = ['CmdlineEnter']
hook_add = '''
let g:traces_normal_preview = v:true
'''

[[plugins]]
repo = 'https://github.com/mattn/vim-lsp-settings'
depends = ['vim-lsp']
on_event = ['BufRead']
hook_add = '''
vim9cmd user#plugins#lsp#HookAdd()
'''
hook_source = '''
if v:vim_did_enter
  call timer_start(0, { -> lsp#enable() })
else
  autocmd vimrc VimEnter * call timer_start(0, { -> lsp#enable() })
endif
'''

[[plugins]]
repo = 'https://github.com/mattn/vim-notification'
on_func = ['notification#']

[[plugins]]
repo = 'https://github.com/obcat/vim-hitspop'
on_event = ['CmdlineLeave']
on_func = ['hitspop#main']
hook_add = '''
let g:hitspop_line = 'winbot'
let g:hitspop_column = 'winleft'
let g:hitspop_timeout = 2000
autocmd vimrc ColorScheme * hi link hitspopErrormsg ErrorMsg
autocmd vimrc User SearchxInputChanged call hitspop#main()
'''

[[plugins]]
repo = 'https://github.com/obcat/vim-sclow'
lazy = true
hook_add = '''
autocmd vimrc VimEnter * ++once call timer_start(0, { -> dein#source('vim-sclow') })
let g:sclow_hide_full_length = v:true
'''

[[plugins]]
repo = 'https://github.com/ojroques/vim-oscyank'
on_func = ['OSCYankRegister']
hook_add = '''
autocmd vimrc TextYankPost *
      \ : if stridx('*+', v:event.regname) > -1
      \ |   call OSCYankRegister(v:event.regname)
      \ | endif
'''

[[plugins]]
repo = 'https://github.com/prabirshrestha/vim-lsp'
on_source = ['vim-lsp-settings']

[[plugins]]
repo = 'https://github.com/rbtnn/vim-coloredit'
on_cmd = ['ColorEdit']
