---
version: 2
lint-debounce: 0.5s
root-markers:
  - .git/
  - .git
tools:
  textlint-lint: &textlint-lint
    prefix: textlint
    lint-command: 'npx --no-install textlint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror/%r]'
      - '%f:%l:%c: 【%r】 %m'
      - '%E%f:%l:%c: %m'
      - '%Z%m [%trror/%r]'
      - '%C%m'
    root-markers:
      - .textlintrc
      - .textlintrc.json
      - .textlintrc.yaml
      - .textlintrc.yml
    commands:
      - title: 'textlint fix'
        command: npx
        arguments:
          - '--no-install'
          - 'textlint'
          - '--fix'
          - '${INPUT}'

  markdownlint-lint: &markdownlint-lint
    prefix: markdownlint
    lint-command: 'npx --no-install markdownlint --stdin'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c MD%n/%*[^ ] %m'
      - '%f:%l MD%n/%*[^ ] %m'
    commands:
      - title: 'markdownlint fix'
        command: markdownlint
        arguments:
          - '--fix'
          - '${INPUT}'

  # jq-format: &jq-format
  #   format-command: 'jq .'
  #   format-stdin: true

  fixjson-format: &fixjson-format
    format-command: 'fixjson'
    format-stdin: true

  stylua-format: &stylua-format
    format-command: 'stylua --config-path $XDG_CONFIG_HOME/stylua/stylua.toml -'
    format-stdin: true

  shellcheck-lint: &shellcheck-lint
    prefix: shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t%*[^:]: %m [SC%n]'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -s -ln bash -i 2 -bn -ci -sr'
    format-stdin: true

  vint-lint: &vint-lint
    prefix: vint
    lint-command: 'vint --enable-neovim --style-problem --stdin-display-name ${INPUT} -'
    lint-stdin: true

languages:
  markdown:
    - <<: *textlint-lint
    - <<: *markdownlint-lint

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  lua:
    - <<: *stylua-format

  json:
    # - <<: *jq-format
    - <<: *fixjson-format

  vim:
    - <<: *vint-lint

  zsh:
    - <<: *shfmt-format

