---
version: 2
lint-debounce: 0.5s
root-markers:
  - .git/
  - .git
tools:
  textlint-lint: &textlint-lint
    prefix: textlint
    lint-command: >
      deno run --allow-all --no-lock --unstable --node-modules-dir
      npm:textlint --cache -f unix --no-color ${INPUT}
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m [%trror/%r]"
      - "%f:%l:%c: 【%r】 %m"
      - "%E%f:%l:%c: %m"
      - "%Z%m [%trror/%r]"
      - "%C%m"
    root-markers:
      - .textlintrc
      - .textlintrc.json
      - .textlintrc.yaml
      - .textlintrc.yml
    commands:
      - title: "textlint fix"
        command: deno
        arguments:
          - run
          - --allow-all
          - --no-lock
          - --unstable
          - --node-modules-dir
          - npm:textlint
          - --cache
          - --fix
          - ${INPUT}

  hadolint-lint: &hadolint-lint
    prefix: hadolint
    lint-command: "hadolint"
    lint-formats:
      - "%f:%l DL%n %t%*[a-z]: %m"

  commitlint-lint: &commitlint-lint
    prefix: commitlint
    lint-command: "npx --no-install commitlint -c false"
    lint-stdin: true
    lint-formats:
      - "%t%*[^ ] %m"
    root-markers:
      - .commitlintrc
      - .commitlintrc.json
      - .commitlintrc.yaml
      - .commitlintrc.yml
      - .commitlintrc.js
      - .commitlintrc.cjs
      - .commitlintrc.ts
      - commitlint.config.js
      - commitlint.config.cjs
      - commitlint.config.ts
    lint-category-map:
      ✖: E
      ⚠: W

  fixjson-format: &fixjson-format
    format-command: deno run -A --no-lock --unstable npm:fixjson
    format-stdin: true

  stylua-format: &stylua-format
    format-command: "stylua --search-parent-directories -"
    format-stdin: true

  shellcheck-lint: &shellcheck-lint
    prefix: shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %t%*[^:]: %m [SC%n]"

  shfmt-format: &shfmt-format
    format-command: "shfmt -s -ln bash -i 2 -bn -ci -sr"
    format-stdin: true

  actionlint-lint: &actionlint-lint
    prefix: actionlint
    lint-command: "bash -c \"[[ '${INPUT}' =~ \\\\.github/workflows/ ]]\" && actionlint -oneline -no-color -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    root-markers:
      - .github

  vint-lint: &vint-lint
    prefix: vint
    lint-command: "vint --enable-neovim --style-problem --stdin-display-name ${INPUT} -"
    lint-stdin: true

languages:
  markdown:
    - <<: *textlint-lint

  dockerfile:
    - <<: *hadolint-lint

  gitcommit:
    - <<: *commitlint-lint

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  lua:
    - <<: *stylua-format

  json:
    - <<: *fixjson-format

  vim:
    - <<: *vint-lint

  yaml:
    - <<: *actionlint-lint

  zsh:
    - <<: *shfmt-format
