name: aqua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: config/aqua/aqua.yaml
      AQUA_LOG_COLOR: always
      AQUA_POLICY_CONFIG: config/aqua/aqua-policy.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      # NOTE: use paths-filter instead of on.pull_request.paths to trigger test always
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            aqua:
              - .github/workflows/aqua.yaml
              - config/aqua/aqua.yaml
              - config/aqua/experimental.yaml
      - name: Install aqua
        if: steps.filter.outputs.aqua == 'true'
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.44.1
      - uses: actions/setup-go@v5
        if: steps.filter.outputs.aqua == 'true'
        with:
          go-version: "1.22.1"
      - name: Run test
        if: steps.filter.outputs.aqua == 'true'
        run: aqua install
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
