---
name: aqua
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: config/aqua/aqua.yaml
      AQUA_LOG_COLOR: always
      AQUA_POLICY_CONFIG: config/aqua/aqua-policy.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # NOTE: use paths-filter instead of on.pull_request.paths to trigger test always
      - name: Check Changed Files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            aqua:
              - ".github/workflows/aqua.yaml"
              - "config/aqua/aqua.yaml"
              - "config/aqua/experimental.yaml"
      - name: Install aqua
        if: steps.filter.outputs.aqua == 'true'
        uses: aquaproj/aqua-installer@v1.1.1
        with:
          aqua_version: v2.20.0
          policy_allow: config/aqua/aqua-policy.yaml
      - name: Set up Golang
        if: steps.filter.outputs.aqua == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.4"
      - name: Run test
        if: steps.filter.outputs.aqua == 'true'
        run: aqua install
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
