---
name: aqua
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/aqua.yaml
      - config/aqua/aqua.yaml
      - config/aqua/experimental.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/aqua.yaml
      - config/aqua/aqua.yaml
      - config/aqua/experimental.yaml
jobs:
  test:
    strategy:
      matrix:
        env:
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: config/aqua/aqua.yaml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/aquaproj-aqua/pkgs
            ~/.local/share/aquaproj-aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('config/aqua/aqua.yaml') }}
      - name: Install aqua
        uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.14.1 # renovate: depName=aquaproj/aqua
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Run test
        run: aqua install --test
        env:
          AQUA_GOARCH: ${{ matrix.env.goarch }}
          AQUA_GOOS: ${{ matrix.env.goos }}
