name: aqua

on:
  push:
    branches:
      - main
    paths:
      - config/aqua/aqua.yaml
  pull_request:
    branches:
      - main
    paths:
      - config/aqua/aqua.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.11.0 # renovate: depName=aquaproj/aqua
      - run: aqua --config config/aqua/aqua.yaml install --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
