---
name: aqua
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/aqua.yaml
      - config/aqua/aqua.yaml
      - config/aqua/experimental.yaml
      - renovate.json
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/aqua.yaml
      - config/aqua/aqua.yaml
      - config/aqua/experimental.yaml
      - renovate.json
jobs:
  test:
    strategy:
      matrix:
        goos:
          - darwin
          - linux
        goarch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: config/aqua/aqua.yaml
      AQUA_LOG_COLOR: always
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # NOTE: cache is too slow
      # - name: Cache packages
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.local/share/aquaproj-aqua/pkgs
      #       ~/.local/share/aquaproj-aqua/registries
      #     key: ${{ runner.os }}-aqua-${{ matrix.goos }}-${{ matrix.goarch }}-${{ hashFiles('config/aqua/aqua.yaml') }}
      - name: Install aqua
        uses: aquaproj/aqua-installer@v1.0.0
        with:
          aqua_version: v1.17.1
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Run test
        run: aqua install --test
        env:
          AQUA_GOARCH: ${{ matrix.goarch }}
          AQUA_GOOS: ${{ matrix.goos }}
