---
name: poetry
on:
  push:
    branches: [main]
    paths:
      - config/python
  pull_request:
    branches: [main]
    paths:
      - config/python
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up python
        id: python
        uses: actions/python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('config/python/poetry.lock') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != "true"
        run: poetry install -vvv --no-interaction --no-root
      - name: Install project
        run: poetry install -vvv --no-interaction
