---
name: udd
on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      NO_COLOR: 1
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Update deno dependencies
        run: >
          deno run --allow-all "https://deno.land/x/udd@0.8.2/main.ts"
          -- ./**/*.ts ./**/*.json ./**/*.yaml .github/**/*.yaml
          | tee ../output.txt
      - name: Read ../output.txt
        id: log
        uses: juliangruber/read-file-action@v1
        with:
          path: ../output.txt
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(deps): update deno dependencies"
          title: "chore(deps): update deno dependencies"
          body: |
            Update deno dependencies by [udd](https://github.com/hayd/deno-udd):

            ```yaml
            ${{ steps.log.outputs.content }}
            ```

            Pull Request is created by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          branch: udd/deno-dependency-updates
          author: GitHub <noreply@github.com>
          labels: dependencies
          delete-branch: true
          token: ${{ secrets.PAT }}
      - name: Enable Pull Request Automerge
        if: steps.pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
          merge-method: squash
